apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployLabel }}
  name: {{ .Values.deployName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployLabel }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: rollingupdate
