global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kube-state-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-35-170-203-121.compute-1.amazonaws.com:30705']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-54-172-98-53.compute-1.amazonaws.com:9100']
  - job_name: 'k8s-node-1'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-35-170-203-121.compute-1.amazonaws.com:9100']
  - job_name: 'k8s-node-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-23-22-184-199.compute-1.amazonaws.com:9100']
