echo -n 'AKIAQEMIJBYFVKRDWLCZ' | base64 -d
echo -n 'NXTyWOBE8aPeMyhKHmVetJMwKf5oy7NwhPri9HQb' | base64

apiVersion: v1
kind: Secret
metadata:
  name: aws-access-keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVFFTUlKQllGVktSRFdMQ1o=
  AWS_SECRET_ACCESS_KEY: TlhUeVdPQkU4YVBlTXloS0htVmV0Sk13S2Y1b3k3TndoUHJpOUhRYg==
  

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-1
spec:
  containers:
    - name: aws-cli-container
      image: sreeharshav/utils:latest
      volumeMounts:
        - name: secret-volume
          mountPath: /tmp/awscreds
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-creds

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-1
spec:
  containers:
    - name: aws-cli-container
      image: sreeharshav/utils:latest
      volumeMounts:
        - name: secret-volume
          mountPath: /tmp/awscreds
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-access-keys
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-access-keys
            key: AWS_SECRET_ACCESS_KEY
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-access-keys
            

kubectl create secret generic mysqlpassword2 --from-literal=mysqlpassword2=India@123456






