apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nottaint2
  name: nottaint2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nottaint2
  template:
    metadata:
      labels:
        app: nottaint2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: perf
                operator: In
                values:
                - high1
                - high2
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "phoenix"
        effect: "NoExecute"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nottaint2
  name: nottaint2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nottaint2
  template:
    metadata:
      labels:
        app: nottaint2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: perf
                operator: In
                values:
                - high1
                - high2
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    PERF: HIGH
  name: nginx02
spec:
  replicas: 30
  selector:
    matchLabels:
      PERF: HIGH
  template:
    metadata:
      labels:
        PERF: HIGH
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: PERF
                operator: In
                values:
                - HIGH
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate