apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: object-counts
 namespace: development
spec:
 hard:
   #compute-resources
   requests.cpu: "1000m"
   limits.cpu: "2000m"
   requests.memory: 1Gi
   limits.memory: 2Gi
   #object-counts
   pods: "5"
   replicationcontrollers: "20"
   resourcequotas: "10"
   services: "5"
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test01
  name: test01
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      run: test01
  template:
    metadata:
      labels:
        run: test01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: test01
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "200m"
