kubectl taint node <node-name> env=temple:NoSchedule
kubectl taint node <node-name> env=factory:NoSchedule
kubectl taint node <node-name> env=madhuloka:NoSchedule


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deploy01
  name: deploy01-temple
spec:
  replicas: 2
  selector:
    matchLabels:
      run: deploy01
  template:
    metadata:
      labels:
        run: deploy01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: deploy01
      tolerations:
         - key: "env"
           operator: "Equal"
           value: "temple"
           effect: "NoSchedule"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deploy01
  name: deploy01-factory-madhuloka
spec:
  replicas: 4
  selector:
    matchLabels:
      run: deploy01
  template:
    metadata:
      labels:
        run: deploy01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: deploy01
      tolerations:
         - key: "env"
           operator: "Equal"
           value: "factory"
           effect: "NoSchedule"
         - key: "env"
           operator: "Equal"
           value: "madhuloka"
           effect: "NoSchedule"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deploy01
  name: deploy01-key-exists
spec:
  replicas: 6
  selector:
    matchLabels:
      run: deploy01
  template:
    metadata:
      labels:
        run: deploy01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: deploy01
      tolerations:
         - key: "env"
           operator: "Exists"
           effect: "NoSchedule"